[project]
name = "client"
version = "0.1.0"
description = "Animal Chess client"
readme = "README.md"
requires-python = "<3.12,>=3.11"
dependencies = [
  "dotenv>=0.9.9",
  "podsixnet>=0.11.0",
  "core",
  "panda3d==1.10.15",
]

[tool.uv.sources]
core = { workspace = true }

[tool.pyright]
venvPath = ".."
venv = "../.venv"
include = [
  "client/*"
]

[tool.hatch.build.targets.wheel]
packages = ["client"]

[tool.hatch.metadata]
allow-direct-references = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
