[project]
name = "core"
version = "0.1.0"
description = "Animal Chess core"
readme = "README.md"
requires-python = "<3.12,>=3.11"
dependencies = [
    "marshmallow-dataclass>=8.7.1",
]

[tool.pyright]
venvPath = ".."
venv = "../.venv"
include = [
  "core/*"
]

[tool.hatch.build.targets.wheel]
packages = ["core"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
